install.packages("knitr")
install.packages("rmarkdown")
install.packages("vegan")
install.packages("ggplot2")
install.packages("ggpubr")
install.packages("reshape2")
install.packages("cowplot")
install.packages("superheat")
install.packages("plyr")
install.packages("dplyr")

source("http://www.bioconductor.org/biocLite.R")
biocLite("DESeq2")
biocLite("phyloseq")

install.packages("devtools")
devtools::install_github("benjjneb/decontam")
